config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  get 'contact/confirm'
  get 'contact/done'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'top#index'
  resources :users, only: %i[new create] do
    get 'post_list', on: :member
  end
  resources :posts, only: %i[new index create show edit update destroy] do
    collection do
      get :likes
    end
  end
  resources :boards, only: %i[new index create show edit update destroy] do
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get 'bird', to: 'static#bird'
  get 'terms', to: 'static#terms'
  get 'policy', to: "static#policy"
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :board_image, BoardImageUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  belongs_to :board
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :message, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PostUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy

  def tag_names
    tags.map(&:name).join(",")
  end

  def save_tags(tag_names)
    tag_names.each do |tag_name|
      tag = Tag.find_or_initialize_by(name: tag_name.strip)

      tags << tag unless tags.include?(tag)
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, uniqueness: { scope: :tag_id }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :tag_relations, dependent: :destroy

  validates :name, length: { in: 1..15 }, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, length: { maximum: 255 }

  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  def own?(object)
    id == object&.user_id
  end

  def like(post)
    like_posts << post
  end

  def unlike(post)
    like_posts.destroy(post)
  end

  def like?(post)
    like_posts.include?(post)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_login

  def create
    post = Post.find(params[:post_id])
    current_user.like(post)
    redirect_to posts_path, success: 'いいねしました！'
  end

  def destroy
    post = current_user.likes.find(params[:id]).post
    current_user.unlike(post)
    redirect_to posts_path, success: 'いいねを解除しました'
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: "ユーザーを変更しました"
    else
      flash.now['danger'] = "ユーザーを変更できませんでした"
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :name)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = '')
    base_title = 'BIRD APP'
    title.present? ? "#{title} | #{base_title}" : base_title
  end

  def default_meta_tags
    {
      site: 'Buncho-Lover',
      title: '文鳥好きや飼うか迷っている方の為の写真投稿や質問・雑談出来るサービス',
      reverse: true,
      charset: 'utf-8',
      description: 'Buncho-Loberでは、文鳥の写真の投稿や、質問・雑談掲示板などを建てリアルタイムで話す事が出来ます。',
      keywords: '文鳥,鳥,小鳥,手乗り',
      canonical: 'https://first-app-bird-e6fdc1b0fdf3.herokuapp.com/',
      separator: '|',
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: 'https://first-app-bird-e6fdc1b0fdf3.herokuapp.com/',
        image: image_url('tori.jpg'),
        local: 'ja-JP'
      },
      twitter: {
        card: 'summary_large_image', # Twitterで表示する場合は大きいカードに変更
        site: '#', # アプリの公式Twitterアカウントがあれば、アカウント名を記載
        image: image_url('tori.jpg') # 配置するパスやファイル名によって変更
      }
    }
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profiles/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <div class="text-container">
        <h1><%= t('.title') %></h1>
        <%= form_with model: @user, url: profile_path, method: :put do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="mb-3">
            <%= f.label :email, class: "form-label" %>
            <%= f.email_field :email, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label :name, class: "form-label" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="d-flex justify-content-end">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<% content_for(:title, t('.title')) %>

<div class="container pt-3">
  <div class="text-container">
    <h1 class="float-left mb-5"><%= current_user.name %>のマイページ</h1>

    <div class="row">
      <div class="col-md-10 offset-md-1">
        <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn btn-success float-right mb-3' %>
        <table class="table">
          <tr>
            <th scope="row"><%= User.human_attribute_name(:email) %></th>
            <td><%= current_user.email %></td>
          </tr>
          <tr>
            <th scope="row"><%= User.human_attribute_name(:name) %></th>
            <td><%= current_user.name %></td>
          </tr>
        </table>
      </div>
    </div>

    <div class="row py-5">
      <div class="d-grid gap-2 col-6 mx-auto">
        <%= link_to "自分の投稿を見る", post_list_user_path(current_user), class: "btn btn-primary btn-lg" %>
      </div>
    </div>

    <div class="row py-3">
      <div class="d-grid gap-2 col-6 mx-auto">
        <%= link_to "いいね、した投稿一覧", likes_posts_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>

  </div> <!-- text-container ends here -->
</div>