config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  get 'contact/confirm'
  get 'contact/done'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'top#index'
  resources :users, only: %i[new create] do
    get 'post_list', on: :member
  end
  resources :posts, only: %i[new index create show edit update destroy] do
    collection do
      get :likes
    end
  end
  resources :boards, only: %i[new index create show edit update destroy] do
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get 'bird', to: 'static#bird'
  get 'terms', to: 'static#terms'
  get 'policy', to: "static#policy"
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :board_image, BoardImageUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  belongs_to :board
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :message, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PostUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy

  def tag_names
    tags.map(&:name).join(",")
  end

  def save_tags(tag_names)
    tag_names.each do |tag_name|
      tag = Tag.find_or_initialize_by(name: tag_name.strip)

      tags << tag unless tags.include?(tag)
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, uniqueness: { scope: :tag_id }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :tag_relations, dependent: :destroy

  validates :name, length: { in: 1..15 }, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, length: { maximum: 255 }

  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  def own?(object)
    id == object&.user_id
  end

  def like(post)
    like_posts << post
  end

  def unlike(post)
    like_posts.destroy(post)
  end

  def like?(post)
    like_posts.include?(post)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
  end

  def update
    @comment = current_user.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("comment-#{@comment.id}", partial: 'comments/comment', locals: { comment: @comment }),
            turbo_stream.remove("comment-edit-#{@comment.id}") # ここで編集フォームを削除
          ]
        end
        format.html { redirect_to board_path(@comment.board) }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("comment-edit-#{@comment.id}", partial: "comments/edit_comment_form", locals: { comment: @comment })
        end
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(board_id: params[:board_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_login

  def create
    post = Post.find(params[:post_id])
    current_user.like(post)
    redirect_to posts_path, success: 'いいねしました！'
  end

  def destroy
    post = current_user.likes.find(params[:id]).post
    current_user.unlike(post)
    redirect_to posts_path, success: 'いいねを解除しました'
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = '')
    base_title = 'BIRD APP'
    title.present? ? "#{title} | #{base_title}" : base_title
  end

  def default_meta_tags
    {
      site: 'Buncho-Lover',
      title: '文鳥好きや飼うか迷っている方の為の写真投稿や質問・雑談出来るサービス',
      reverse: true,
      charset: 'utf-8',
      description: 'Buncho-Loberでは、文鳥の写真の投稿や、質問・雑談掲示板などを建てリアルタイムで話す事が出来ます。',
      keywords: '文鳥,鳥,小鳥,手乗り',
      canonical: 'https://first-app-bird-e6fdc1b0fdf3.herokuapp.com/',
      separator: '|',
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: 'https://first-app-bird-e6fdc1b0fdf3.herokuapp.com/',
        image: image_url('tori.jpg'),
        local: 'ja-JP'
      },
      twitter: {
        card: 'summary_large_image', # Twitterで表示する場合は大きいカードに変更
        site: '#', # アプリの公式Twitterアカウントがあれば、アカウント名を記載
        image: image_url('tori.jpg') # 配置するパスやファイル名によって変更
      }
    }
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.erb
<tr id="comment-<%= comment.id %>">
  <td>
    <h3 class="small"><%= comment.user.name %></h3>
    <p><%= simple_format(comment.body) %></p>
    <p class="text-muted small text-end">
      <%= l(comment.created_at, format: :short2) %>
    </p>
  </td>
  <% if current_user.own?(comment) %>
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to edit_comment_path(comment), class: "edit-comment-link", data: { turbo_frame: "comment-edit-#{comment.id}" } do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
        </li>
        <li class="list-inline-item">
          <%= link_to comment_path(comment), class: "delete-comment-link", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>
<turbo-frame id="comment-edit-<%= comment.id %>"></turbo-frame>

app/views/comments/_edit_comment_form.html.erb
<turbo-frame_tag id="comment-edit-<%= comment.id %>">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <%= form_with model: comment, url: comment_path(comment), method: :patch, local: false do |f| %>
        <%= hidden_field_tag 'board_id', comment.board_id %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :body, t('comments.edit_body_label') %>
        <%= f.text_area :body, class: "form-control mb-3", rows: 4, placeholder: Comment.human_attribute_name(:body) %>
        <%= f.submit t('defaults.update'), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</turbo-frame>

app/views/comments/_form.html.erb
<div class="row mb-3" id="comment-form">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: comment, url: board_comments_path(board) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control mb-3", row: "4", placeholder: Comment.human_attribute_name(:body) %>
      <%= f.submit t('defaults.post'), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/comments/create.turbo_stream.erb
<% if @comment.errors.present? %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: @comment, board: @comment.board %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "table-comment" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: Comment.new, board: @comment.board %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment-#{@comment.id}" do %>
<% end %>

app/views/comments/edit.html.erb
<turbo-frame id="comment-edit-<%= @comment.id %>">
  <%= render 'edit_comment_form', comment: @comment, board: @comment.board %>
</turbo-frame>

app/views/comments/update.tutbo_stream.erb
<% if @comment.errors.present? %>
  <%= turbo_stream.replace "comment-form-#{@comment.id}" do %>
    <%= render partial: 'comments/edit_comment_form', locals: { comment: @comment } %>
  <% end %>
<% else %>
  <%= turbo_stream.replace dom_id(@comment} do %>
    <%= render partial: 'comments/comment', locals: { comment: @comment } %>
  <% end %>
<% end %>