config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  get 'contact/confirm'
  get 'contact/done'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'top#index'
  resources :users, only: %i[new create] do
    get 'post_list', on: :member
  end
  resources :posts, only: %i[new index create show edit update destroy] do
    collection do
      get :likes
    end
  end
  resources :boards, only: %i[new index create show edit update destroy] do
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get 'bird', to: 'static#bird'
  get 'terms', to: 'static#terms'
  get 'policy', to: "static#policy"
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :board_image, BoardImageUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  belongs_to :board
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :message, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PostUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy

  def tag_names
    tags.map(&:name).join(",")
  end

  def save_tags(tag_names)
    tag_names.each do |tag_name|
      tag = Tag.find_or_initialize_by(name: tag_name.strip)

      tags << tag unless tags.include?(tag)
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, uniqueness: { scope: :tag_id }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :tag_relations, dependent: :destroy

  validates :name, length: { in: 1..15 }, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, length: { maximum: 255 }

  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  def own?(object)
    id == object&.user_id
  end

  def like(post)
    like_posts << post
  end

  def unlike(post)
    like_posts.destroy(post)
  end

  def like?(post)
    like_posts.include?(post)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = '')
    base_title = 'BIRD APP'
    title.present? ? "#{title} | #{base_title}" : base_title
  end

  def default_meta_tags
    {
      site: 'Buncho-Lover',
      title: '文鳥好きや飼うか迷っている方の為の写真投稿や質問・雑談出来るサービス',
      reverse: true,
      charset: 'utf-8',
      description: 'Buncho-Loberでは、文鳥の写真の投稿や、質問・雑談掲示板などを建てリアルタイムで話す事が出来ます。',
      keywords: '文鳥,鳥,小鳥,手乗り',
      canonical: 'https://first-app-bird-e6fdc1b0fdf3.herokuapp.com/',
      separator: '|',
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: 'https://first-app-bird-e6fdc1b0fdf3.herokuapp.com/',
        image: image_url('tori.jpg'),
        local: 'ja-JP'
      },
      twitter: {
        card: 'summary_large_image', # Twitterで表示する場合は大きいカードに変更
        site: '#', # アプリの公式Twitterアカウントがあれば、アカウント名を記載
        image: image_url('tori.jpg') # 配置するパスやファイル名によって変更
      }
    }
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-CCR4QSNVSC"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-CCR4QSNVSC');
    </script>

    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= display_meta_tags(default_meta_tags) %>
  </head>

  <body>
  <div class="all-back-image">
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/not_login_header' %>
    <% end %>

    <div class="breadcrumbs">
      <%= breadcrumbs separator: " &rsaquo; " %>
    </div>
      <%= render 'shared/flash_message' %>
    <%= yield %>
  </div>
      <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# フッター %>
<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <!-- ロゴやアイコン部分 -->
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24">
        <title>Bird-Lover</title>
        <circle cx="12" cy="12" r="10"/>
        <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/>
      </svg>
      <small class="d-block mb-3 text-muted">&copy; 2024 Bird-Lover</small>
    </div>
    
    <!-- 利用規約のリンク -->
    <div class="col-6 col-md">
      <ul class="list-unstyled text-small">
        <li><%= link_to '利用規約', terms_path, class: "link-secondary" %></li>
      </ul>
    </div>
    
    <!-- プライバシーポリシーのリンク -->
    <div class="col-6 col-md ms-md-auto">
      <ul class="list-unstyled text-small">
        <li><%= link_to 'プライバシーポリシー', policy_path, class: "link-secondary" %></li>
      </ul>
    </div>

    <!-- お問い合わせのリンク -->
    <div class="col-6 col-md">
      <ul class="list-unstyled text-small">
        <li><%= link_to 'お問い合わせ', new_contact_path, class: "link-secondary" %></li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <%# navbar %>
  <nav class="navbar navbar-expand-md" style="background-color: #e3f2fd;" >
    <div class="container-fluid">
      <%# navbar-brandではアプリ名やアプリの画像などを設定する %>
      <%= link_to "<i class='bi bi-bird'></i> Buncho-Lover".html_safe, root_path, class: "navbar-brand" %>
      <%# ハンバーガーメニュー %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <%# 左に表示されるもの %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class='navbar-nav ms-auto main-nav align-items-center'>
          <li class='nav-item dropdown dropdown-slide'>
            <%= link_to "投稿", '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-board-menu' %>
            <div class='dropdown-menu dropdown-menu-end'>
              <%= link_to '投稿一覧', posts_path, class: 'dropdown-item' %>
              <%= link_to '新規投稿', new_post_path, class: 'dropdown-item' %>
            </div>
          </li>
          <li class='nav-item dropdown dropdown-slide'>
            <%= link_to "掲示板", '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-board-menu' %>
            <div class='dropdown-menu dropdown-menu-end'>
              <%= link_to '掲示板一覧', boards_path, class: 'dropdown-item' %>
              <%= link_to '掲示板投稿', new_board_path, class: 'dropdown-item' %>
            </div>
          </li>
        </ul>

        <%# 右に表示されるもの %>
        <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'ログアウト', logout_path, class: 'nav-link', data: { turbo_method: :delete } %>
          </li>
          <li class="nav-item ml-3">
            <%= link_to 'マイページ', profile_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_not_login_header.html.erb
<header>
  <%# navbar %>
  <nav class="navbar navbar-expand-md" style="background-color: #e3f2fd;" >
    <div class="container-fluid">
      <%# navbar-brandではアプリ名やアプリの画像などを設定する %>
      <%= link_to "Buncho-Lover", root_path, class: "navbar-brand" %>
      <%# ハンバーガーメニュー %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class="nav-item ml-3">
          <%= link_to t('header.login'), login_path, class: "nav-link" %>
        </li>
        <li class="nav-item ml-3">
          <%= link_to "Googleアカウントでログイン", auth_at_provider_path(provider: :google), class: "nav-link" %>
        </li>
        <li class="nav-item ml-3">
          <%= link_to t('header.new_registration'), new_user_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>