config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  get 'contact/confirm'
  get 'contact/done'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'top#index'
  resources :users, only: %i[new create] do
    get 'post_list', on: :member
  end
  resources :posts, only: %i[new index create show edit update destroy] do
    collection do
      get :likes
    end
  end
  resources :boards, only: %i[new index create show edit update destroy] do
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get 'bird', to: 'static#bird'
  get 'terms', to: 'static#terms'
  get 'policy', to: "static#policy"
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PostUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy

  def tag_names
    tags.map(&:name).join(",")
  end

  def save_tags(tag_names)
    tag_names.each do |tag_name|
      tag = Tag.find_or_initialize_by(name: tag_name.strip)

      tags << tag unless tags.include?(tag)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: %i[index show]

  def index
    @posts = if params[:tag_names]
               Post.joins(:tags).where(tags: { name: params[:tag_names] }).includes(:user).order(created_at: :desc).page(params[:page])
             else
               Post.includes(:user).order(created_at: :desc).page(params[:page])
             end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
    @tag_names = @post.tags.map(&:name).join(", ")
  end

  def create
    @post = current_user.posts.new(post_params)
    tag_names = params[:tag_names].split(",")

    if @post.save
      @post.save_tags(tag_names)
      redirect_to post_path(@post), success: '投稿を作成しました'
    else
      flash.now[:danger] = '投稿を作成できませんでした'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post = current_user.posts.find(params[:id])
    tag_names = params[:tag_names].split(",")
    tags = tag_names.map { |tag_name| Tag.find_or_create_by(name: tag_name) }

    tags.each do |tag|
      next unless tag.invalid?

      @tag_names = params[:tag_names]
      @post.errors.add(:tags, tag.errors.full_messages.join("\n"))
      return render :edit, status: :unprocessable_entity
    end

    if @post.update(post_params) && @post.update!(tags:)
      redirect_to post_path(@post), success: '投稿を更新しました'
    else
      @tag_names = params[:tag_names]
      flash.now[:danger] = '投稿を更新できませんでした'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, success: '投稿を削除しました', status: :see_other
  end

  def likes
    @like_posts = current_user.like_posts.includes(:user).order(created_at: :desc).page(params[:page])
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :image_cache)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like_buttun.html.erb
<div class='ms-auto'>
  <% if current_user && current_user.like?(post) %>
    <%= render 'ok_like', { post: post } %>
  <% else %>
    <%= render 'no_like', { post: post } %>
  <% end %>
</div>

app/views/posts/_no_like.html.erb
<%= link_to likes_path(post_id: post.id), id: "like-button-for-post-#{post.id}", data: { turbo_method: :post } do %>
  <i class="bi bi-chat-square-heart"></i>
<% end %>

app/views/posts/_ok_like.html.erb
<%= link_to like_path(current_user.likes.find_by(post_id: post.id)), id: "unlike-button-for-post-#{post.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-chat-square-heart-fill"></i>
<% end %>

app/views/posts/_post_form.html.erb
<%= form_with model: @post, class: "new_post" do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", rows: "5" %>
  </div>
  <div class="mb-3">
    <%= label :tag_names, 'タグ' %>
    <%= text_field_tag :tag_names, @post.tag_names, class: 'form-control', placeholder: ",で区切って入力してください" %>
  </div>
  <div class="mb-3">
    <%= f.label :image, class: "form-label" %>
    <%= f.file_field :image, class: "form-control", accept: 'image/*' %>
    <%= f.hidden_field :image_cache %>
  </div>
  <%= f.submit nil, class: "btn btn-primary" %>
<% end %>

app/views/posts/_post_index.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="post-id-<%= post.id %>">
    <div class="card">
      <% if post.image? %>
        <%= image_tag post.image.url, class: "card-img-top", width: "300", height: "200" %>
      <% else %>
        <%= image_tag "post_placeholder.png", class: "card-img-top", width: "300", height: "200" %>
      <% end %>
      <div class="card-body">
        <div class="d-flex">
          <h4 class="card-title">
            <%= link_to post.title, post_path(post) %>
          </h4>
          <% if current_user && current_user.own?(post) %>
            <div class='ms-auto'>
              <%= link_to edit_post_path(post), id: "button-edit-#{post.id}" do %>
                <i class="bi bi-pencil-fill"></i>
              <% end %>
              <%= link_to post_path(post), id: "button-delete-#{post.id}", data: { turbo_method: :delete, turbo_confirm: '削除しますか？' } do %>
                <i class="bi bi-trash-fill"></i>
              <% end %>
            </div>
          <% else %>
            <%= render 'like_buttun', post: post %>
          <% end %>
        </div>
        <div class="d-flex">
          <div class='ms-auto'>
            <% post.tags.each do |tag| %>
              <%= link_to tag.name, posts_path(tag_names: tag.name), class: "btn btn-primary btn-sm" %>
            <% end %>
          </div>
        </div>
        <ul class="list-inline">
          <li class="list-inline-item">
            <i class="bi bi-person"></i>
            <%= link_to "by #{post.user.name}", post_list_user_path(post.user), class: "btn btn-link" %>
          </li>
          <li class="list-inline-item">
            <i class="bi bi-calendar"></i>
            <%= l post.created_at, format: :short %>
          </li>
        </ul>
        <p class="card-text"><%= post.body %></p>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <div class="text-container">
        <h1><%= t('.title') %></h1>
        <%= render 'post_form', post: @post, tag_name: @tag_name %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>
<% breadcrumb :posts %>

<div class="container pt-3">
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="text-container">
      <h1>みんなの投稿一覧</h1>
      <div class="col-12">
        <div class="row">
          <% if @posts.present? %>
            <% @posts.each do |post| %>
              <%= render partial: 'post_index', locals: { post: post } %>
            <% end %>
          <% else %>
            <div class="mb-3">投稿がありません</div>
          <% end %>
        </div>
        <%= paginate @posts, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/likes.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- セクションの内容はここに追加 -->
    </div>
  </div>
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="text-container col-12">
      <div class="row">
        <% if @like_posts.present? %>
          <%= render partial: 'post_index', collection: @like_posts, as: :post %>
        <% else %>
          <p><%= t('.no_like') %></p>
        <% end %>
      </div>
      <%= paginate @like_posts, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <div class="text-container">
        <h1><%= t('.title') %></h1>
        <%= render 'post_form', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for(:title, @post.title) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <div class="text-container">
        <h1><%= t('.title') %></h1>
        <article class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-md-7">
                <!-- image_tagを使って画像を表示 -->
                <%= image_tag @post.image? ? @post.image.url : "post_placeholder.png", 
                    class: "card-img-top", 
                    width: "300", 
                    height: "200" %>
              </div>
              <div class="col-md-9">
                <h3 style="display: inline;"><%= @post.title %></h3>
                <ul class="list-inline">
                  <li class="list-inline-item">
                    <%= link_to "by #{@post.user.name}", post_list_user_url(@post.user) %>
                  </li>
                  <li class="list-inline-item"><%= l @post.created_at, format: :short %></li>
                </ul>
                <% if current_user && current_user.own?(@post) %>
                  <div class='d-flex justify-content-end'>
                    <%= link_to edit_post_path(@post), id: "button-edit-#{@post.id}" do %>
                      <i class="bi bi-pencil-fill"></i>
                    <% end %>
                    <%= link_to post_path(@post), id: "button-delete-#{@post.id}", data: { turbo_method: :delete, turbo_confirm: '削除しますか？'} do %>
                      <i class="bi bi-trash-fill"></i>
                    <% end %>
                  </div>
                <% else %>
                  <div class="d-flex">
                    <div class='ms-auto'>
                      <%= render 'like_buttun', { post: @post } %>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="d-flex">
                <div class='ms-auto'>
                  <% @post.tags.each do |tag| %>
                    <%= link_to tag.name, posts_path(tag_name: tag.name), class: "btn btn-primary btn-sm" %>
                  <% end %>
                </div>
              </div>
            </div>
            <p><%= simple_format(@post.body) %></p>
          </div>
        </article>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="d-grid gap-2 col-2 offset-md-2">
      <div class="text-container">
        <%= link_to "https://twitter.com/share?url=#{post_url(@post)}&text=【2Seeds】%0a%0a#{@post.title}", 
                    target: '_blank', 
                    data: { toggle: "tooltip", placement: "bottom" }, 
                    title: "Xでシェア", 
                    class: "btn btn-outline-primary btn-lg d-flex align-items-center justify-content-center" do %>
          <i class="fab fa-twitter me-2"></i> Xシェア
        <% end %>
      </div>
    </div>
  </div>
</div>